### ISSUE TITLE
Discord RPC Plugin

### ISSUE THREAD

**Issue by sr229** [vincelwt/harmony-plugins#1]
I'm willing to voluntarily make this since it's nice to have your playing status with Discord RPC (just like how Spotify does it).

**Comment by vincelwt** [comment]
Nice :) This repo is deprecated (old versions of plugins) tho you may want to check these ones: https://github.com/topics/harmony-plugin

Let me know if you encounter issues

**Comment by sr229** [comment]
Thanks @vincelwt, will close this issue in favor of a seperate repo
